
services:
  nexus:
    container_name: "nexus"
    image: sonatype/nexus
    hostname: nexus
    ports:
      - 0.0.0.0:8081:8081/tcp
    volumes:
      - nexus-data:/nexus-data:rw
    user: nexus


volumes:
  nexus-data:
  