services:
  nexus:
    container_name: "nexus"
    image: sonatype/nexus
    hostname: nexus
    ports:
      - 0.0.0.0:8081:8081/tcp
    volumes:
      - nexus-data:/nexus-data:rw
    user: nexus
  nginx:
    container_name: "nginx"
    image: nginx:latest
    hostname: nginx
    volumes:
      - ./nginx/nexus.conf:/etc/nginx/conf.d/nexus.conf:ro
    ports:
      - "0.0.0.0:80:80/tcp"
      - "0.0.0.0:443:443/tcp"


volumes:
  nexus-data:
    external: true
    name: nexus-data