services:
  nexus:
    container_name: "nexus"
    image: sonatype/nexus3
    hostname: nexus
    networks:
      - nexus
    ports:
      - 0.0.0.0:8081:8081/tcp
    volumes:
      - nexus-data:/nexus-data:rw
    user: nexus
  nginx:
    container_name: "nginx"
    image: nginx:latest
    hostname: nginx
    networks:
      - nexus
    volumes:
      - ./nginx/nexus.conf:/etc/nginx/conf.d/nexus.conf:rw
      - ./certs/nexus.crt:/etc/nginx/certs/cert.crt:ro
      - ./certs/nexus.key:/etc/nginx/certs/cert_key.key:ro
    ports:
      - "0.0.0.0:80:80/tcp"
      - "0.0.0.0:443:443/tcp"


volumes:
  nexus-data:
    external: true
    name: nexus-data

networks:
  nexus:
    name: "nexus-network"
